spring:
  application:
    name: muma-backend
  jpa:
    open-in-view: false

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env
  endpoint:
    health:
      show-details: always

spotify:
  base-url: https://api.spotify.com/v1
  client-id: ${SPOTIFY_CLIENT_ID:}
  client-secret: ${SPOTIFY_CLIENT_SECRET:}
