spring:
  application:
    name: muma-backend
  datasource:
    url: jdbc:h2:file:./data/muma
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env
  endpoint:
    health:
      show-details: always

spotify:
  base-url: https://api.spotify.com/v1
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
